CRYPTO_COINS = {'NXS': 'Nexus', 'UBQ': 'Ubiq', 'LKK': 'Lykke', 'NEO': 'NEO',
'CLOAK': 'CloakCoin', 'ZEC': 'Zcash', 'BTC': 'Bitcoin', 'DASH': 'Dash',
'BLOCK': 'Blocknet', 'MIOTA': 'IOTA', 'XVG': 'Verge', 'PIVX': 'PIVX',
'SYS': 'Syscoin', 'BCC': 'BitConnect', 'XMR': 'Monero',
'GBYTE': 'Byteball Bytes', 'XRP': 'Ripple', 'NLG': 'Gulden', 'KMD': 'Komodo',
'WAVES': 'Waves', 'NXT': 'Nxt', 'HSR': 'Hshare', 'LTC': 'Litecoin',
'STRAT': 'Stratis', 'IOC': 'I/O Coin', 'STEEM': 'Steem', 'BCH': 'Bitcoin Cash',
'SC': 'Siacoin', 'PART': 'Particl', 'FCT': 'Factom', 'ETC': 'Ethereum Classic',
'FAIR': 'FairCoin', 'ARK': 'Ark', 'GXS': 'GXShares', 'BTS': 'BitShares',
'BCN': 'Bytecoin', 'XLM': 'Stellar Lumens', 'LSK': 'Lisk', 'XEM': 'NEM',
'DGB': 'DigiByte', 'DCR': 'Decred', 'NLC2': 'NoLimitCoin', 'OK': 'OKCash',
'BTCD': 'BitcoinDark', 'NAV': 'NAV Coin', 'DOGE': 'Dogecoin',
'GAME': 'GameCredits', 'ETH': 'Ethereum', 'FRST': 'FirstCoin', 'XEL': 'Elastic'}

CURRENCIES = {'RON': 'Romanian Leu', 'LSL': 'Loti', 'YER': 'Yemeni Rial',
'MZN': 'Mozambique Metical', 'PYG': 'Guarani', 'DZD': 'Algerian Dinar',
'NIO': 'Cordoba Oro', 'STD': 'Dobra', 'AOA': 'Kwanza', 'UAH': 'Hryvnia',
'ISK': 'Iceland Krona', 'GHS': 'Ghana Cedi', 'THB': 'Baht', 'GTQ': 'Quetzal',
'JOD': 'Jordanian Dinar', 'XAU': 'Gold', 'COU': 'Unidad de Valor Real',
'XUA': 'ADB Unit of Account', 'PHP': 'Philippine Peso', 'IQD': 'Iraqi Dinar',
'QAR': 'Qatari Rial', 'VND': 'Dong', 'AED': 'UAE Dirham',
'XBB': 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
'INR': 'Indian Rupee', 'TWD': 'New Taiwan Dollar', 'MYR': 'Malaysian Ringgit',
'PGK': 'Kina', 'MVR': 'Rufiyaa', 'EGP': 'Egyptian Pound',
'LKR': 'Sri Lanka Rupee', 'USD': 'US Dollar', 'BND': 'Brunei Dollar',
'TRY': 'Turkish Lira', 'CAD': 'Canadian Dollar', 'MWK': 'Malawi Kwacha',
'BSD': 'Bahamian Dollar', 'NGN': 'Naira', 'MGA': 'Malagasy Ariary',
'RSD': 'Serbian Dinar', 'BAM': 'Convertible Mark', 'BOV': 'Mvdol',
'XAF': 'CFA Franc BEAC', 'BHD': 'Bahraini Dinar',
'SBD': 'Solomon Islands Dollar', 'SLL': 'Leone',
'XDR': 'SDR (Special Drawing Right)', 'MRO': 'Ouguiya', 'BDT': 'Taka',
'OMR': 'Rial Omani', 'VEF': 'Bolívar', 'TJS': 'Somoni',
'KYD': 'Cayman Islands Dollar', 'RUB': 'Russian Ruble',
'CUC': 'Peso Convertible', 'NZD': 'New Zealand Dollar', 'AMD': 'Armenian Dram',
'LAK': 'Lao Kip', 'SYP': 'Syrian Pound', 'XCD': 'East Caribbean Dollar',
'SHP': 'Saint Helena Pound', 'KHR': 'Riel',
'XBC': 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
'ZMW': 'Zambian Kwacha', 'BOB': 'Boliviano', 'KRW': 'Won',
'CNY': 'Yuan Renminbi', 'MKD': 'Denar', 'XAG': 'Silver', 'CHW': 'WIR Franc',
'CZK': 'Czech Koruna', 'BBD': 'Barbados Dollar', 'XPF': 'CFP Franc',
'UYU': 'Peso Uruguayo', 'MNT': 'Tugrik', 'BYN': 'Belarusian Ruble',
'JMD': 'Jamaican Dollar', 'GBP': 'Pound Sterling',
'MXV': 'Mexican Unidad de Inversion (UDI)', 'BRL': 'Brazilian Real',
'KGS': 'Som', 'PAB': 'Balboa', 'KPW': 'North Korean Won',
'FJD': 'Fiji Dollar', 'BIF': 'Burundi Franc', 'DKK': 'Danish Krone',
'SCR': 'Seychelles Rupee', 'ETB': 'Ethiopian Birr', 'KES': 'Kenyan Shilling',
'CHF': 'Swiss Franc', 'BMD': 'Bermudian Dollar', 'MOP': 'Pataca', 'ALL': 'Lek',
'TOP': 'Pa’anga', 'USN': 'US Dollar (Next day)', 'UGX': 'Uganda Shilling',
'AWG': 'Aruban Florin', 'MMK': 'Kyat', 'TMT': 'Turkmenistan New Manat',
'FKP': 'Falkland Islands Pound', 'JPY': 'Yen', 'BTN': 'Ngultrum',
'VUV': 'Vatu', 'AZN': 'Azerbaijan Manat',
'XBA': 'Bond Markets Unit European Composite Unit (EURCO)',
'SAR': 'Saudi Riyal', 'WST': 'Tala', 'DOP': 'Dominican Peso',
'SOS': 'Somali Shilling', 'PLN': 'Zloty', 'SZL': 'Lilangeni',
'CRC': 'Costa Rican Colon', 'AFN': 'Afghani', 'HKD': 'Hong Kong Dollar',
'TZS': 'Tanzanian Shilling', 'GMD': 'Dalasi', 'KMF': 'Comorian Franc ',
'HTG': 'Gourde', 'COP': 'Colombian Peso', 'XSU': 'Sucre',
'MDL': 'Moldovan Leu', 'CDF': 'Congolese Franc', 'SDG': 'Sudanese Pound',
'PEN': 'Sol', 'BWP': 'Pula', 'GYD': 'Guyana Dollar', 'UYI':
'Uruguay Peso en Unidades Indexadas (URUIURUI)', 'ZAR': 'Rand',
'ANG': 'Netherlands Antillean Guilder', 'SSP': 'South Sudanese Pound',
'EUR': 'Euro', 'CUP': 'Cuban Peso', 'MAD': 'Moroccan Dirham', 'HUF': 'Forint',
'SVC': 'El Salvador Colon', 'GIP': 'Gibraltar Pound', 'RWF': 'Rwanda Franc',
'XPD': 'Palladium', 'SRD': 'Surinam Dollar', 'CLF': 'Unidad de Fomento',
'HNL': 'Lempira', 'DJF': 'Djibouti Franc', 'UZS': 'Uzbekistan Sum',
'LYD': 'Libyan Dinar', 'KZT': 'Tenge', 'HRK': 'Kuna', 'GEL': 'Lari',
'XBD': 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
'BZD': 'Belize Dollar', 'ERN': 'Nakfa', 'BGN': 'Bulgarian Lev',
'XOF': 'CFA Franc BCEAO', 'LBP': 'Lebanese Pound', 'MXN': 'Mexican Peso',
'MUR': 'Mauritius Rupee', 'CVE': 'Cabo Verde Escudo',
'SGD': 'Singapore Dollar', 'IDR': 'Rupiah', 'ARS': 'Argentine Peso',
'TND': 'Tunisian Dinar', 'IRR': 'Iranian Rial', 'NPR': 'Nepalese Rupee',
'ILS': 'New Israeli Sheqel', 'KWD': 'Kuwaiti Dinar', 'CLP': 'Chilean Peso',
'PKR': 'Pakistan Rupee', 'GNF': 'Guinean Franc', 'AUD': 'Australian Dollar',
'LRD': 'Liberian Dollar', 'NOK': 'Norwegian Krone', 'SEK': 'Swedish Krona',
'NAD': 'Namibia Dollar', 'ZWL': 'Zimbabwe Dollar',
'TTD': 'Trinidad and Tobago Dollar', 'CHE': 'WIR Euro', 'XPT': 'Platinum'}
